### ISSUE TITLE
Remove turbolinks.

### ISSUE THREAD

**Issue by sergiotapia** [PCMRating/pcmrating#35]
Turbolinks is terrible and makes for a bad user experience. I just clicked on the logo to go to the home page and it sorta froze. I didn't know if it was loading or if some sort of javascript click handler was crashing. 

Turbolinks is a bad idea and should be nuked! :metal:

**Comment by thesbros** [comment]
You clicked the logo once and it froze so it's a bad idea? I can't seem to reproduce this.

**Comment by sergiotapia** [comment]
Well, no that's not the only reason. I was being cheeky. Turbolinks fucks around with lots of different jquery plugins as well - that's it's most damning feature. 

It was created to bring client side framework speed but in exchange causes lots of unwanted behavior. Trust me, it's bitten my ass multiple times on multiple projects.

**Comment by sergiotapia** [comment]
But don't take my word for it: http://stackoverflow.com/questions/14231616/what-are-the-pros-and-cons-of-asset-pipeline-turbolinks-from-rails-4-for-a-big-a

**Comment by Ruxton** [comment]
:+1:  turbolinks, ugh.  get rid of it!

The default configurations of turbolinks are not my favourite thing in the world. The common browsing behaviours are thrown out the window with turbolinks enabled.  All the statuses my browser fires are gone.

If you're on a fast connection, all this is fine, everything happens so fast the status bar doesn't even register to you.  But get on a real slow connection, these common browser behaviours of loading icons and the status bar are a persons life line to knowing what's happening.  Turbolinks throws them all out the window, in favour of nothing.

There's also issues that happen where closing and returning to the page you've visited via turbolinks can sometimes have the JSON response being shown on screen instead of the correctly styled page.  

It also screws with a lot of standard jQuery libraries that lean on document ready, this can be patched and worked around, but why incur that extra effort? what's the benefit?

**Comment by Lockyy** [comment]
I completely agree. Definitely needs removing. It's great in a fresh project but as soon as you introduce anything interesting it inevitably breaks things. +1

**Comment by sergiotapia** [comment]
Fixed in #41 :rocket:
